import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { cn } from "@/lib/utils";
import { ThemeToggle } from "@/components/ThemeToggle";
import { AuthSessionProvider } from "@/components/session-provider";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <>
      <html lang="en">
        <head />
        <body className={cn("font-sans antialiased dark", inter.variable)}>
          <AuthSessionProvider>{children}</AuthSessionProvider>
          <Toaster richColors />
          <ThemeToggle className="fixed top-1 right-1 mt-2 mr-1" />
        </body>
      </html>
    </>
  );
}
